### ISSUE TITLE
Skiylia Grammar

### ISSUE THREAD

**Issue by SK1Y101** [Skiylia-Lang/PySkiylia#25]
**Is your feature request related to a problem? Please describe.**
Skiylia does not yet have well defined grammar (outside of my head of course)

**Describe the solution you'd like**
A document in one form or another that adequately lays out the gramatical structure for Skiylia.

**Additional context**
While this does not have to be exhaustitive yet (as Skiylia is still mutable) It should at least be conscise.

**Comment by skyecas** [comment]
This has since been dealt with as per commit dd834e7
